# fly.toml app configuration file generated for bsdsec on 2023-08-07T10:58:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bsdsec"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs", "heroku/ruby"]
  [build.args]
    SECRET_KEY_BASE = "asdf"

[deploy]
  release_command = "rails db:migrate"

[processes]
  app = "puma -C config/puma.rb"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
